### ISSUE TITLE
`ServerHandle::stop(true)` future never completes, server never shuts down

### ISSUE THREAD

**Issue by alexschrod** [actix/actix-net#419]
Using `HttpServer::disable_signals()` followed by a later call to `ServerHandle::stop(true)` results in a future that never completes, and the process hangs until you close it forcefully. MRE to reproduce the problem follows:

Cargo.toml
```toml
[package]
name = "shutdown-mre"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0-beta.11"
tokio = "1.12"
```

main.rs
```rust
use actix_web::{web, App, HttpResponse, HttpServer};

#[actix_web::main]
async fn main() {
    // Start HTTP server
    let http_server = HttpServer::new(move || App::new().default_service(web::route().to(index)))
        .disable_signals()
        .bind("0.0.0.0:3000")
        .unwrap()
        .run();

    println!("Server started!");

    let ctrl_c = tokio::signal::ctrl_c();
    ctrl_c.await.unwrap();

    println!("Asking server to shut down!");

    let http_server_handle = http_server.handle();
    http_server_handle.stop(true).await;

    println!("We're shut down!");
}

async fn index() -> actix_web::Result<HttpResponse> {
    Ok(HttpResponse::Ok().body("Hello, world!"))
}
```

Output is
```
Server started!
  <Ctrl+C pressed>
Asking server to shut down!
  <hangs forever until killed>
```
