### ISSUE TITLE
Graceful shutdown not finishing - stuck on "Shutting down idle worker"

### ISSUE THREAD

**Issue by joepio** [actix/actix-net#428]
Hi there! Thanks for maintaining this. I use actix with a lot of pleasure. 

Since I've updated to the latest betas, graceful shutdown seems broken. The logs say: `Shutting down idle worker`, but then nothing happens. 

Versions:

```toml
actix-rt = "2.4.0"
actix-web = "4.0.0-beta.12"
actix = "0.12.0"
actix-cors = "0.6.0-beta.4"
actix-files = "0.6.0-beta.9"
actix-web-actors = "4.0.0-beta.7"
```

Project: [atomic-server](https://github.com/joepio/atomic-data-rust/) `cargo install atomic-server`
